sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g truffle ganache-cli

script:
  - ganache-cli -l 8000000 2> /dev/null 1> /dev/null &
  - truffle test
